<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
//    public function save(array $options = [])
//    {
//        return parent::save($options); // TODO: Change the autogenerated stub
//    }
//
//    public function update(array $attributes = [], array $options = [])
//    {
//        return parent::update($attributes, $options); // TODO: Change the autogenerated stub
//    }

    protected $fillable = [
        'username',
        'text'
        //      'published_at'
//        'gravatar',
//        'created_at',
//        'updated_at'

    ];
    //
}
